config/routes.rb
Rails.application.routes.draw do
  root to: 'common#index'
  resources :users
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    validates :device_model, :imei, :anual_price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :cpf, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/common_controller.rb
class CommonController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  require 'rest_client'

  API_BASE_URL = "http://localhost:3000/api/v1"

  def index
    uri = "#{API_BASE_URL}/orders.json"
    rest_resource = RestClient::Resource.new(uri)
    orders = rest_resource.get 
    @orders = JSON.parse(orders, :symbolize_names => true)
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.valid?
        uri = "#{API_BASE_URL}/orders"
        payload = params.to_json
        rest_resource = RestClient::Resource.new(uri)
        begin
          rest_resource.post payload , :content_type => "application/json"
          format.html { redirect_to @order, notice: 'Order was successfully created.' }
          format.json { render :show, status: :created, location: @order }
        rescue Exception => e
          logger.debug e
          @order.errors.add(:fail, e)
          format.html { render :new }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    uri = "#{API_BASE_URL}/orders/#{params[:id]}"
    rest_resource = RestClient::Resource.new(uri)
    begin
      rest_resource.delete
      flash[:notice] = "Order Deleted successfully"
    rescue Exception => e
      flash[:error] = "Order Failed to Delete"
    end
    redirect_to orders_path
  end

  private
  def order_params
    params.require(:order).permit(:device_model, :imei, :anual_price, :installments)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'rest_client'

  API_BASE_URL = "http://localhost:3000/api/v1"

  def index
    uri = "#{API_BASE_URL}/users.json"
    rest_resource = RestClient::Resource.new(uri)
    users = rest_resource.get 
    @users = JSON.parse(users, :symbolize_names => true)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.valid?
        uri = "#{API_BASE_URL}/users"
        payload = params.to_json
        rest_resource = RestClient::Resource.new(uri)
        begin
          resp = rest_resource.post payload , :content_type => "application/json"
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        rescue Exception => e
          logger.debug resp
          @user.errors.add(:fail, e)
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    uri = "#{API_BASE_URL}/users/#{params[:id]}"
    rest_resource = RestClient::Resource.new(uri)
    begin
      rest_resource.delete
      flash[:notice] = "User Deleted successfully"
    rescue Exception => e
      flash[:error] = "User Failed to Delete"
    end
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :cpf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_helper.rb
module CommonHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/index.html.erb
<h1>Teste para Pitzi</h1>
<br/>
<p> <h5>Link Front:</h5> <a href="https://github.com/linknys/pitzi-front-t">https://github.com/linknys/pitzi-front-t </a></p>
<p> <h5>Link API: </h5><a href="https://github.com/linknys/pitzi-api">https://github.com/linknys/pitzi-api </a> </p>
<br/><br/>
<p>- Porta API:   3000
<br/>
<p>- Porta FRONT: 3001
<br/><br/>
<p> <h5> Endpoints: </h5> 
<p> <a href="https://drive.google.com/file/d/14BqtCTbOw_oJv9P5FcBcDBrzIZ5DFs2Y/view?usp=sharing">https://drive.google.com/file/d/14BqtCTbOw_oJv9P5FcBcDBrzIZ5DFs2Y/view?usp=sharing </a>
<br/> (Salvar e importar no Postman caso queira testar diretamente)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pitzi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Home", brand_link: root_url do %>
      <%= menu_group do %>
        <%= menu_item "Create Order", new_order_path %>
      <% end %>
      <%= menu_group do %>
        <%= menu_item "Create User", new_user_path %>
      <% end %>
      <%= menu_group do %>
        <%= menu_item "Orders", orders_path %>
      <% end %>
      <%= menu_group do %>
        <%= menu_item "Users", users_path %>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_model %>
    <%= form.text_field :device_model %>
  </div>

  <div class="field">
    <%= form.label :imei %>
    <%= form.text_field :imei %>
  </div>

  <div class="field">
    <%= form.label :anual_price %>
    <%= form.text_field :anual_price %>
  </div>

  <div class="field">
    <%= form.label :installments %>
    <%= form.number_field :installments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Device model</td>
            <td>Imei</td>
            <td>Anual price</td>
            <td>Installments</td>
            <td colspan="1">
        </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
        <tr>
            <td><%= order[:device_model] %></td>
            <td><%= order[:imei] %></td>
            <td><%= order[:anual_price] %></td>
            <td><%= order[:installments] %></td>
            <td><%= link_to 'Destroy', order_path(order[:id]), method: :delete, data: { confirm: "Are you sure you want to delete order #{order[:device_model]}?" } %></td>
        <tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device model:</strong>
  <%= @order.device_model %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @order.imei %>
</p>

<p>
  <strong>Anual price:</strong>
  <%= @order.anual_price %>
</p>

<p>
  <strong>Installments:</strong>
  <%= @order.installments %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Cpf</td>
            <td colspan="1">
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= user[:name] %></td>
            <td><%= user[:email] %></td>
            <td><%= user[:cpf] %></td>
            <td><%= link_to 'Destroy', user_path(user[:id]), method: :delete, data: { confirm: "Are you sure you want to delete user with CPF #{user[:cpf]}?" } %></td>
        <tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @user.cpf %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>